apiVersion: v1

kind: Service

metadata:
  app: react-vite-docker-k8s

spec:
  type: NodePort
  selector:
    app: react-vite-docker-k8s
  ports:
    - ports: 5173
      targetPort: 5173
      NodePort: 30007